import React, { useState, useRef, useEffect } from 'react';
import { generateWallpaper } from './services/geminiService';
import { ChatMessage, Role, AspectRatio } from './types';
import { Button } from './components/Button';
import { 
  Send, 
  Image as ImageIcon, 
  Smartphone, 
  Monitor, 
  Download, 
  Trash2,
  Wand2,
  RefreshCw,
  X,
  Edit,
  Grid,
  Square
} from 'lucide-react';

const App: React.FC = () => {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [aspectRatio, setAspectRatio] = useState<AspectRatio>('9:16');
  const [imageCount, setImageCount] = useState<1 | 4>(1);
  const [attachedImage, setAttachedImage] = useState<string | null>(null);
  
  // Modal State
  const [selectedImage, setSelectedImage] = useState<string | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const chatContainerRef = useRef<HTMLDivElement>(null);

  // "Mona Lisa" Frame Style Definition
  const MUSEUM_FRAME_STYLE: React.CSSProperties = {
    borderWidth: '12px',
    borderStyle: 'ridge',
    borderColor: '#785c38', // Antique Gold/Walnut
    boxShadow: 'inset 0 0 20px rgba(0,0,0,0.8), 2px 2px 10px rgba(0,0,0,0.5)',
    borderRadius: '4px' // Slight rounding
  };

  // Auto-scroll to bottom of chat
  useEffect(() => {
    if (chatContainerRef.current) {
      chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
    }
  }, [messages]);

  // Initial greeting
  useEffect(() => {
    const initialMessage: ChatMessage = {
      id: 'init',
      role: Role.MODEL,
      text: "Hello Ram! I'm your AI Art Director. I can generate or edit wallpapers for you. Try saying 'A futuristic city' or upload an image and say 'Add a retro filter'.",
      timestamp: Date.now(),
    };
    setMessages([initialMessage]);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setAttachedImage(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const clearAttachment = () => {
    setAttachedImage(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const handleEditImage = (imgBase64: string) => {
    setAttachedImage(imgBase64);
    setSelectedImage(null); // Close modal
    // Focus input
    const input = document.querySelector('textarea');
    if (input) input.focus();
  };

  const handleSend = async () => {
    if ((!inputValue.trim() && !attachedImage) || isLoading) return;

    const userMsgId = Date.now().toString();
    const newUserMsg: ChatMessage = {
      id: userMsgId,
      role: Role.USER,
      text: inputValue,
      images: attachedImage ? [attachedImage] : undefined,
      timestamp: Date.now(),
    };

    // Determine the base image for editing
    // Priority: 
    // 1. Currently attached image (explicit edit)
    // 2. Last generated AI image (implicit edit) - ONLY if single image history is clear
    let baseImageForApi = attachedImage;

    if (!baseImageForApi) {
      // Look backwards for the last image generated by the model
      const lastModelMsg = [...messages].reverse().find(m => m.role === Role.MODEL && m.images && m.images.length > 0);
      if (lastModelMsg && lastModelMsg.images && lastModelMsg.images.length > 0) {
        // Default to the first image of the last batch if implicit
        baseImageForApi = lastModelMsg.images[0];
      }
    }

    setMessages(prev => [...prev, newUserMsg]);
    setInputValue('');
    setAttachedImage(null); // Clear manual attachment after sending
    setIsLoading(true);

    try {
      const result = await generateWallpaper({
        prompt: newUserMsg.text || "Enhance this image",
        baseImageBase64: baseImageForApi || undefined,
        aspectRatio: aspectRatio,
        count: imageCount,
      });

      const aiMsgId = (Date.now() + 1).toString();
      const newAiMsg: ChatMessage = {
        id: aiMsgId,
        role: Role.MODEL,
        text: result.text,
        images: result.images,
        timestamp: Date.now(),
      };

      setMessages(prev => [...prev, newAiMsg]);
    } catch (error) {
      console.error(error);
      const errorMsg: ChatMessage = {
        id: (Date.now() + 2).toString(),
        role: Role.MODEL,
        text: "Sorry, I encountered an error generating your wallpaper. Please try again.",
        timestamp: Date.now(),
      };
      setMessages(prev => [...prev, errorMsg]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div className="flex flex-col h-screen max-w-4xl mx-auto bg-slate-900 shadow-2xl overflow-hidden md:border-x md:border-slate-800 relative">
      
      {/* Header */}
      <header className="p-4 bg-slate-900/90 backdrop-blur-md border-b border-slate-800 sticky top-0 z-20 flex flex-wrap gap-3 justify-between items-center">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-indigo-600 rounded-lg">
            <Wand2 className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="font-bold text-lg text-white leading-tight">Ultimate Wallpaper Gen</h1>
            <p className="text-xs text-slate-400">Gemini 2.5 Flash Image</p>
          </div>
        </div>
        
        <div className="flex items-center gap-2">
           {/* Image Count Toggle */}
           <div className="flex bg-slate-800 p-1 rounded-lg border border-slate-700 mr-2">
            <button
              onClick={() => setImageCount(1)}
              className={`flex items-center justify-center w-8 h-8 rounded-md transition-all ${
                imageCount === 1 ? 'bg-indigo-600 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200'
              }`}
              title="Generate 1 Image"
            >
              <Square className="w-4 h-4" />
            </button>
            <button
              onClick={() => setImageCount(4)}
              className={`flex items-center justify-center w-8 h-8 rounded-md transition-all ${
                imageCount === 4 ? 'bg-indigo-600 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200'
              }`}
               title="Generate 4 Images"
            >
              <Grid className="w-4 h-4" />
            </button>
          </div>

          {/* Aspect Ratio Toggle */}
          <div className="flex bg-slate-800 p-1 rounded-lg border border-slate-700 gap-0.5">
            <button
              onClick={() => setAspectRatio('9:16')}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm transition-all ${
                aspectRatio === '9:16' ? 'bg-indigo-600 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200'
              }`}
              title="Mobile (9:16)"
            >
              <Smartphone className="w-4 h-4" />
              <span className="hidden sm:inline">Mobile</span>
            </button>
            <button
              onClick={() => setAspectRatio('9:19.5')}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm transition-all ${
                aspectRatio === '9:19.5' ? 'bg-indigo-600 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200'
              }`}
              title="Mobile Full (9:19.5)"
            >
              <Smartphone className="w-4 h-4 scale-y-110" />
              <span className="hidden sm:inline">Full</span>
            </button>
            <button
              onClick={() => setAspectRatio('16:9')}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm transition-all ${
                aspectRatio === '16:9' ? 'bg-indigo-600 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200'
              }`}
              title="Desktop (16:9)"
            >
              <Monitor className="w-4 h-4" />
              <span className="hidden sm:inline">Desktop</span>
            </button>
          </div>
        </div>
      </header>

      {/* Chat Area */}
      <main ref={chatContainerRef} className="flex-1 overflow-y-auto p-4 space-y-6 scroll-smooth">
        {messages.map((msg) => (
          <div
            key={msg.id}
            className={`flex ${msg.role === Role.USER ? 'justify-end' : 'justify-start'}`}
          >
            <div
              className={`max-w-[85%] md:max-w-[75%] rounded-2xl p-4 ${
                msg.role === Role.USER
                  ? 'bg-indigo-600 text-white rounded-br-none'
                  : 'bg-slate-800 border border-slate-700 text-slate-200 rounded-bl-none'
              }`}
            >
              {msg.text && <p className="whitespace-pre-wrap mb-2 leading-relaxed text-sm">{msg.text}</p>}
              
              {/* Display Images Grid */}
              {msg.images && msg.images.length > 0 && (
                <div className={`grid gap-2 mt-2 ${msg.images.length > 1 ? 'grid-cols-2' : 'grid-cols-1'}`}>
                  {msg.images.map((img, idx) => (
                    <div 
                      key={idx} 
                      className="relative group overflow-hidden bg-slate-900 aspect-[9/16] cursor-pointer"
                      style={MUSEUM_FRAME_STYLE}
                      onClick={() => setSelectedImage(img)}
                    >
                      {/* Blurred Background Layer */}
                      <div 
                        className="absolute inset-0 bg-cover bg-center blur-xl opacity-40 scale-125 transition-opacity"
                        style={{ backgroundImage: `url(${img})` }}
                      />
                      
                      {/* Main Image Layer - Object Contain */}
                      <img
                        src={img}
                        alt={`Generated content ${idx + 1}`}
                        className="relative w-full h-full object-contain z-10 transition-transform duration-300 group-hover:scale-105"
                      />
                      
                      <div className="absolute inset-0 z-20 bg-black/0 group-hover:bg-black/20 transition-colors flex items-center justify-center opacity-0 group-hover:opacity-100">
                         <span className="text-white bg-black/50 px-3 py-1 rounded-full text-xs backdrop-blur-sm">Click to View</span>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        ))}
        {isLoading && (
          <div className="flex justify-start">
            <div className="bg-slate-800 rounded-2xl rounded-bl-none p-4 border border-slate-700">
               <div className="flex gap-1.5 items-center">
                 <div className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                 <div className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                 <div className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
               </div>
            </div>
          </div>
        )}
      </main>

      {/* Input Area */}
      <footer className="p-4 bg-slate-900 border-t border-slate-800">
        
        {/* Attachment Preview */}
        {attachedImage && (
          <div className="mb-3 flex items-center gap-3 p-2 bg-slate-800 rounded-lg border border-slate-700 w-fit animate-in slide-in-from-bottom-2">
            <div className="relative w-12 h-12 rounded overflow-hidden">
               <img src={attachedImage} alt="Attachment" className="w-full h-full object-cover" />
            </div>
            <div className="flex flex-col">
              <span className="text-xs text-slate-400 font-medium">Image attached</span>
              <span className="text-[10px] text-slate-500">Ready to edit</span>
            </div>
            <button 
              onClick={clearAttachment}
              className="p-1 hover:bg-red-500/20 text-slate-400 hover:text-red-400 rounded ml-2"
            >
              <Trash2 className="w-4 h-4" />
            </button>
          </div>
        )}

        <div className="flex gap-2 items-end">
          <div className="flex-1 relative">
            <input
              type="file"
              accept="image/*"
              className="hidden"
              ref={fileInputRef}
              onChange={handleFileUpload}
            />
            <button
              onClick={() => fileInputRef.current?.click()}
              className="absolute left-3 bottom-3 text-slate-400 hover:text-indigo-400 transition-colors p-2 hover:bg-slate-700/50 rounded-lg"
              title="Upload reference image"
            >
              <ImageIcon className="w-5 h-5" />
            </button>
            <textarea
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder={attachedImage ? "Describe how to edit this image..." : "Describe a wallpaper..."}
              className="w-full bg-slate-800 text-white placeholder-slate-500 border border-slate-700 rounded-xl pl-12 pr-4 py-3.5 focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none resize-none min-h-[56px] max-h-32"
              rows={1}
            />
          </div>
          <Button 
            onClick={handleSend} 
            disabled={(!inputValue && !attachedImage) || isLoading}
            className="h-[56px] w-[56px] rounded-xl flex-shrink-0 !px-0"
          >
             {isLoading ? <RefreshCw className="w-5 h-5 animate-spin" /> : <Send className="w-5 h-5" />}
          </Button>
        </div>
      </footer>

      {/* Fullscreen Image Modal */}
      {selectedImage && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/95 backdrop-blur-md p-4 animate-in fade-in duration-200">
          <div className="absolute inset-0" onClick={() => setSelectedImage(null)} />
          
          <div className="relative w-full max-w-lg h-[85vh] flex flex-col items-center pointer-events-none">
             {/* Image Container with Blurred Background AND FRAME */}
             <div 
               className="relative w-full flex-1 overflow-hidden shadow-2xl bg-slate-900 mb-6 pointer-events-auto"
               style={MUSEUM_FRAME_STYLE}
             >
                <div 
                   className="absolute inset-0 bg-cover bg-center blur-2xl opacity-50 scale-110" 
                   style={{ backgroundImage: `url(${selectedImage})` }} 
                />
                <img 
                  src={selectedImage} 
                  alt="Full screen" 
                  className="relative w-full h-full object-contain z-10"
                />
             </div>
             
             <div className="flex gap-4 pointer-events-auto">
               <button 
                 onClick={() => handleEditImage(selectedImage)}
                 className="flex items-center gap-2 px-6 py-3 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium shadow-lg shadow-indigo-500/20 transition-all transform hover:scale-105"
               >
                 <Edit className="w-5 h-5" />
                 Edit This Image
               </button>
               
               <a 
                 href={selectedImage} 
                 download={`wallpaper-${Date.now()}.png`}
                 className="flex items-center gap-2 px-6 py-3 bg-slate-700 hover:bg-slate-600 text-white rounded-xl font-medium border border-slate-600 transition-all"
               >
                 <Download className="w-5 h-5" />
                 Download
               </a>
             </div>

             <button 
               onClick={() => setSelectedImage(null)}
               className="absolute -top-4 -right-4 md:-right-12 p-2 text-white/70 hover:text-white bg-white/10 hover:bg-white/20 rounded-full transition-all pointer-events-auto"
             >
               <X className="w-6 h-6" />
             </button>
          </div>
        </div>
      )}

    </div>
  );
};

export default App;